# Generated by Django 3.2.5 on 2022-06-21 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_address', models.CharField(max_length=128)),
                ('house_area', models.FloatField()),
                ('house_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=128)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_telephone', models.CharField(max_length=128)),
                ('user_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.house')),
            ],
        ),
    ]
