# Generated by Django 3.2.5 on 2022-07-11 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_inputtext'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_address', models.CharField(max_length=128)),
                ('property_city', models.CharField(max_length=128)),
                ('property_postcode', models.CharField(max_length=128)),
                ('property_type', models.CharField(max_length=128)),
                ('property_num_bedroom', models.IntegerField()),
                ('property_price', models.FloatField()),
                ('house_date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='user_house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.property'),
        ),
        migrations.DeleteModel(
            name='House',
        ),
    ]
