# Generated by Django 3.2.5 on 2022-07-11 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_auto_20220711_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='house_date',
            new_name='property_date',
        ),
    ]
