# Generated by Django 3.2.5 on 2022-07-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_rename_house_date_property_property_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_house',
            new_name='user_property',
        ),
        migrations.AlterField(
            model_name='inputtext',
            name='input_text',
            field=models.CharField(max_length=512),
        ),
    ]
