# Generated by Django 3.2.5 on 2022-07-11 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_auto_20220711_1802'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
