# Generated by Django 3.2.5 on 2022-07-11 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbot', '0007_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_belong',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_belong', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='property_interested',
            field=models.ManyToManyField(null=True, related_name='user_interested', to=settings.AUTH_USER_MODEL),
        ),
    ]
