# Generated by Django 3.2.5 on 2022-07-11 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbot', '0009_alter_property_property_interested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='property_interested',
        ),
        migrations.AddField(
            model_name='property',
            name='property_interested',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_interested', to=settings.AUTH_USER_MODEL),
        ),
    ]
