# Generated by Django 3.2.5 on 2022-07-11 20:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbot', '0010_auto_20220711_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='property_interested',
        ),
        migrations.AddField(
            model_name='property',
            name='property_interested',
            field=models.ManyToManyField(null=True, related_name='user_interested', to=settings.AUTH_USER_MODEL),
        ),
    ]
